name: flutter_ecommerce_app
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.7.2

#---------------------- PACKAGES ----------------------#
dependencies:
  flutter:
    sdk: flutter

  # Unility Packages


  # Icons 
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8

  # State Management
  get: ^4.3.8

  # Product Specific Packages


#---------------------- PACKAGES END ----------------------#
dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true


#---------------------- LOCAL ASSETS ----------------------#
  assets:
    - assets/fonts/
    - assets/logos/
    - assets/images/
    - assets/icons/brands/
    - assets/icons/categories/


#---------------------- LOCAL FONTS ----------------------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
          style: italic
#---------------------- LOCAL FONTS END ----------------------#