// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-Mmpur9jkCxaI66h0f42bydf--_dHJhI',
    appId: '1:316982410585:web:b7e90823a940234f7d6048',
    messagingSenderId: '316982410585',
    projectId: 'ecommerceapp-994de',
    authDomain: 'ecommerceapp-994de.firebaseapp.com',
    storageBucket: 'ecommerceapp-994de.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgyqCm0IUqusP88Vv_fdEvtBrDtlb28MM',
    appId: '1:316982410585:android:b267fa159b3a94757d6048',
    messagingSenderId: '316982410585',
    projectId: 'ecommerceapp-994de',
    storageBucket: 'ecommerceapp-994de.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDW-r0ftN9xbGSCQp85pbFO4l-LeRX_IBg',
    appId: '1:316982410585:ios:8c1f171d45c6680a7d6048',
    messagingSenderId: '316982410585',
    projectId: 'ecommerceapp-994de',
    storageBucket: 'ecommerceapp-994de.firebasestorage.app',
    androidClientId: '316982410585-d5sm8bepfpjjr7ikjh1mf58u8367n5ee.apps.googleusercontent.com',
    iosClientId: '316982410585-maebkj5ticufpmc34i0hpcpah82ldoei.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterEcommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDW-r0ftN9xbGSCQp85pbFO4l-LeRX_IBg',
    appId: '1:316982410585:ios:8c1f171d45c6680a7d6048',
    messagingSenderId: '316982410585',
    projectId: 'ecommerceapp-994de',
    storageBucket: 'ecommerceapp-994de.firebasestorage.app',
    androidClientId: '316982410585-d5sm8bepfpjjr7ikjh1mf58u8367n5ee.apps.googleusercontent.com',
    iosClientId: '316982410585-maebkj5ticufpmc34i0hpcpah82ldoei.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterEcommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-Mmpur9jkCxaI66h0f42bydf--_dHJhI',
    appId: '1:316982410585:web:beabe9a2491184397d6048',
    messagingSenderId: '316982410585',
    projectId: 'ecommerceapp-994de',
    authDomain: 'ecommerceapp-994de.firebaseapp.com',
    storageBucket: 'ecommerceapp-994de.firebasestorage.app',
  );

}